version: "3"
services:
  discovery-server:
    image: discovery-server
    ports:
      - "8761:8761"
  weatherservice:
    image: weatherservice
    ports:
      - "8088:8088"
    depends_on:
      - discovery-server
  currencyservice:
    image: currencyservice
    ports:
      - "8089:8089"
    depends_on:
      - discovery-server
  predictservice:
    image: predictservice
    ports:
      - "8090:8090"
    depends_on:
      - discovery-server
      - weatherservice
      - currencyservice
