apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      name: currency
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: alenmarz/currencyservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089

---

apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: currency
  type: ClusterIP
