apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaservice
  template:
    metadata:
      name: eurekaservice
      labels:
        app: eurekaservice
    spec:
      containers:
        - name: eurekaservice
          image: alenmarz/eurekaservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eurekaservice
  type: ClusterIP
