apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eurekaservice
  template:
    metadata:
      name: eurekaservice
      labels:
        app: eurekaservice
    spec:
      containers:
        - name: eurekaservice
          image: alenmarz/eurekaservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
