apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictservice
  template:
    metadata:
      name: predictservice
      labels:
        app: predictservice
    spec:
      containers:
        - name: predictservice
          image: alenmarz/predictservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
