apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictservice
  template:
    metadata:
      name: predictservice
      labels:
        app: predictservice
    spec:
      containers:
        - name: predictservice
          image: alenmarz/predictservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: predict
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: predictservice
  type: ClusterIP
