apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      name: weather
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: alenmarz/weatherservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
---

apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: weather
  type: ClusterIP
